const counries = [

{name  = 'Afghanistan',                                                 Alpha2= 'AF', Alpha3 = 'AFG', Numeric = '004'},
{name  = 'Albania',                                                     Alpha2= 'AL', Alpha3 = 'ALB', Numeric = '008'},
{name  = 'Algeria',                                                     Alpha2= 'DZ', Alpha3 = 'DZA', Numeric = '012'},
{name  = 'American Samoa',                                              Alpha2= 'AS', Alpha3 = 'ASM', Numeric = '016'},
{name  = 'Andorra',                                                     Alpha2= 'AD', Alpha3 = 'AND', Numeric = '020'},
{name  = 'Angola',                                                      Alpha2= 'AO', Alpha3 = 'AGO', Numeric = '024'},
{name  = 'Anguilla',                                                    Alpha2= 'AI', Alpha3 = 'AIA', Numeric = '660'},
{name  = 'Antarctica',                                                  Alpha2= 'AQ', Alpha3 = 'ATA', Numeric = '010'},
{name  = 'Antigua and Barbuda',                                         Alpha2= 'AG', Alpha3 = 'ATG', Numeric = '028'},
{name  = 'Argentina',                                                   Alpha2= 'AR', Alpha3 = 'ARG', Numeric = '032'},
{name  = 'Armenia',                                                     Alpha2= 'AM', Alpha3 = 'ARM', Numeric = '051'},
{name  = 'Aruba',                                                       Alpha2= 'AW', Alpha3 = 'ABW', Numeric = '533'},
{name  = 'Australia',                                                   Alpha2= 'AU', Alpha3 = 'AUS', Numeric = '036'},
{name  = 'Austria',                                                     Alpha2= 'AT', Alpha3 = 'AUT', Numeric = '040'},
{name  = 'Azerbaijan',                                                  Alpha2= 'AZ', Alpha3 = 'AZE', Numeric = '031'},
{name  = 'Bahamas(the)',                                                Alpha2= 'BS', Alpha3 = 'BHS', Numeric = '044'},
{name  = 'Bahrain',                                                     Alpha2= 'BH', Alpha3 = 'BHR', Numeric = '048'},
{name  = 'Bangladesh',                                                  Alpha2= 'BD', Alpha3 = 'BGD', Numeric = '050'},
{name  = 'Barbados',                                                    Alpha2= 'BB', Alpha3 = 'BRB', Numeric = '052'},
{name  = 'Belarus',                                                     Alpha2= 'BY', Alpha3 = 'BLR', Numeric = '112'},
{name  = 'Belgium',                                                     Alpha2= 'BE', Alpha3 = 'BEL', Numeric = '056'},
{name  = 'Belize',                                                      Alpha2= 'BZ', Alpha3 = 'BLZ', Numeric = '084'},
{name  = 'Benin',                                                       Alpha2= 'BJ', Alpha3 = 'BEN', Numeric = '204'},
{name  = 'Bermuda',                                                     Alpha2= 'BM', Alpha3 = 'BMU', Numeric = '060'},
{name  = 'Bhutan',                                                      Alpha2= 'BT', Alpha3 = 'BTN', Numeric = '064'},
{name  = 'Bolivia(Plurinational State of)',                             Alpha2= 'BO', Alpha3 = 'BOL', Numeric = '068'},
{name  = 'Bonaire Sint Eustatius and Saba',                             Alpha2= 'BQ', Alpha3 = 'BES', Numeric = '535'},
{name  = 'Bosnia and Herzegovina',                                      Alpha2= 'BA', Alpha3 = 'BIH', Numeric = '070'},
{name  = 'Botswana',                                                    Alpha2= 'BW', Alpha3 = 'BWA', Numeric = '072'},
{name  = 'Bouvet Island',                                               Alpha2= 'BV', Alpha3 = 'BVT', Numeric = '074'},
{name  = 'Brazil',                                                      Alpha2= 'BR', Alpha3 = 'BRA', Numeric = '076'},
{name  = 'British Indian Ocean Territory (the)',                        Alpha2= 'IO', Alpha3 = 'IOT', Numeric = '086'},
{name  = 'Brunei Darussalam',                                           Alpha2= 'BN', Alpha3 = 'BRN', Numeric = '096'},
{name  = 'Bulgaria',                                                    Alpha2= 'BG', Alpha3 = 'BGR', Numeric = '100'},
{name  = 'Burkina Faso',                                                Alpha2= 'BF', Alpha3 = 'BFA', Numeric = '854'},
{name  = 'Burundi',                                                     Alpha2= 'BI', Alpha3 = 'BDI', Numeric = '108'},
{name  = 'Cabo Verde',                                                  Alpha2= 'CV', Alpha3 = 'CPV', Numeric = '132'},
{name  = 'Cambodia',                                                    Alpha2= 'KH', Alpha3 = 'KHM', Numeric = '116'},
{name  = 'Cameroon',                                                    Alpha2= 'CM', Alpha3 = 'CMR', Numeric = '120'},
{name  = 'Canada',                                                      Alpha2= 'CA', Alpha3 = 'CAN', Numeric = '124'},
{name  = 'Cayman Islands (the)',                                        Alpha2= 'KY', Alpha3 = 'CYM', Numeric = '136'},
{name  = 'Central African Republic (the)',                              Alpha2= 'CF', Alpha3 = 'CAF', Numeric = '140'},
{name  = 'Chad',                                                        Alpha2= 'TD', Alpha3 = 'TCD', Numeric = '148'},
{name  = 'Chile',                                                       Alpha2= 'CL', Alpha3 = 'CHL', Numeric = '152'},
{name  = 'China',                                                       Alpha2= 'CN', Alpha3 = 'CHN', Numeric = '156'},
{name  = 'Christmas Island',                                            Alpha2= 'CX', Alpha3 = 'CXR', Numeric = '162'},
{name  = 'Cocos (Keeling) Islands (the)',                               Alpha2= 'CC', Alpha3 = 'CCK', Numeric = '166'},
{name  = 'Colombia',                                                    Alpha2= 'CO', Alpha3 = 'COL', Numeric = '170'},
{name  = 'Comoros (the)',                                               Alpha2= 'KM', Alpha3 = 'COM', Numeric = '174'},
{name  = 'Congo (the Democratic Republic of the)',                      Alpha2= 'CD', Alpha3 = 'COD', Numeric = '180'},
{name  = 'Congo (the)',                                                 Alpha2= 'CG', Alpha3 = 'COG', Numeric = '178'},
{name  = 'Cook Islands (the)',                                          Alpha2= 'CK', Alpha3 = 'COK', Numeric = '184'},
{name  = 'Costa Rica',                                                  Alpha2= 'CR', Alpha3 = 'CRI', Numeric = '188'},
{name  = 'Croatia',                                                     Alpha2= 'HR', Alpha3 = 'HRV', Numeric = '191'},
{name  = 'Cuba',                                                        Alpha2= 'CU', Alpha3 = 'CUB', Numeric = '192'},
{name  = 'Curaçao',                                                     Alpha2= 'CW', Alpha3 = 'CUW', Numeric = '531'},
{name  = 'Cyprus',                                                      Alpha2= 'CY', Alpha3 = 'CYP', Numeric = '196'},
{name  = 'Czechia',                                                     Alpha2= 'CZ', Alpha3 = 'CZE', Numeric = '203'},
{name  = 'Côte d Ivoire',                                               Alpha2= 'CI', Alpha3 = 'CIV', Numeric = '384'},
{name  = 'Denmark',                                                     Alpha2= 'DK', Alpha3 = 'DNK', Numeric = '208'},
{name  = 'Djibouti',                                                    Alpha2= 'DJ', Alpha3 = 'DJI', Numeric = '262'},
{name  = 'Dominica',                                                    Alpha2= 'DM', Alpha3 = 'DMA', Numeric = '212'},
{name  = 'Dominican Republic (the)',                                    Alpha2= 'DO', Alpha3 = 'DOM', Numeric = '214'},
{name  = 'Ecuador',                                                     Alpha2= 'EC', Alpha3 = 'ECU', Numeric = '218'},
{name  = 'Egypt',                                                       Alpha2= 'EG', Alpha3 = 'EGY', Numeric = '818'},
{name  = 'El Salvador',                                                 Alpha2= 'SV', Alpha3 = 'SLV', Numeric = '222'},
{name  = 'Equatorial Guinea',                                           Alpha2= 'GQ', Alpha3 = 'GNQ', Numeric = '226'},
{name  = 'Eritrea',                                                     Alpha2= 'ER', Alpha3 = 'ERI', Numeric = '232'},
{name  = 'Estonia',                                                     Alpha2= 'EE', Alpha3 = 'EST', Numeric = '233'},
{name  = 'Eswatini',                                                    Alpha2= 'SZ', Alpha3 = 'SWZ', Numeric = '748'},
{name  = 'Ethiopia',                                                    Alpha2= 'ET', Alpha3 = 'ETH', Numeric = '231'},
{name  = 'Falkland Islands (the) [Malvinas]',                           Alpha2= 'FK', Alpha3 = 'FLK', Numeric = '238'},
{name  = 'Faroe Islands (the)',                                         Alpha2= 'FO', Alpha3 = 'FRO', Numeric = '234'},
{name  = 'Fiji',                                                        Alpha2= 'FJ', Alpha3 = 'FJI', Numeric = '242'},
{name  = 'Finland',                                                     Alpha2= 'FI', Alpha3 = 'FIN', Numeric = '246'},
{name  = 'France',                                                      Alpha2= 'FR', Alpha3 = 'FRA', Numeric = '250'},
{name  = 'French Guiana',                                               Alpha2= 'GF', Alpha3 = 'GUF', Numeric = '254'},
{name  = 'French Polynesia',                                            Alpha2= 'PF', Alpha3 = 'PYF', Numeric = '258'},
{name  = 'French Southern Territories (the)',                           Alpha2= 'TF', Alpha3 = 'ATF', Numeric = '260'},
{name  = 'Gabon',                                                       Alpha2= 'GA', Alpha3 = 'GAB', Numeric = '266'},
{name  = 'Gambia (the)',                                                Alpha2= 'GM', Alpha3 = 'GMB', Numeric = '270'},
{name  = 'Georgia',                                                     Alpha2= 'GE', Alpha3 = 'GEO', Numeric = '268'},
{name  = 'Germany',                                                     Alpha2= 'DE', Alpha3 = 'DEU', Numeric = '276'},
{name  = 'Ghana',                                                       Alpha2= 'GH', Alpha3 = 'GHA', Numeric = '288'},
{name  = 'Gibraltar',                                                   Alpha2= 'GI', Alpha3 = 'GIB', Numeric = '292'},
{name  = 'Greece',                                                      Alpha2= 'GR', Alpha3 = 'GRC', Numeric = '300'},
{name  = 'Greenland',                                                   Alpha2= 'GL', Alpha3 = 'GRL', Numeric = '304'},
{name  = 'Grenada',                                                     Alpha2= 'GD', Alpha3 = 'GRD', Numeric = '308'},
{name  = 'Guadeloupe',                                                  Alpha2= 'GP', Alpha3 = 'GLP', Numeric = '312'},
{name  = 'Guam',                                                        Alpha2= 'GU', Alpha3 = 'GUM', Numeric = '316'},
{name  = 'Guatemala',                                                   Alpha2= 'GT', Alpha3 = 'GTM', Numeric = '320'},
{name  = 'Guernsey',                                                    Alpha2= 'GG', Alpha3 = 'GGY', Numeric = '831'},
{name  = 'Guinea',                                                      Alpha2= 'GN', Alpha3 = 'GIN', Numeric = '324'},
{name  = 'Guinea-Bissau',                                               Alpha2= 'GW', Alpha3 = 'GNB', Numeric = '624'},
{name  = 'Guyana',                                                      Alpha2= 'GY', Alpha3 = 'GUY', Numeric = '328'},
{name  = 'Haiti',                                                       Alpha2= 'HT', Alpha3 = 'HTI', Numeric = '332'},
{name  = 'Heard Island and McDonald Islands',                           Alpha2= 'HM', Alpha3 = 'HMD', Numeric = '334'},
{name  = 'Holy See (the)',                                              Alpha2= 'VA', Alpha3 = 'VAT', Numeric = '336'},
{name  = 'Honduras',                                                    Alpha2= 'HN', Alpha3 = 'HND', Numeric = '340'},
{name  = 'Hong Kong',                                                   Alpha2= 'HK', Alpha3 = 'HKG', Numeric = '344'},
{name  = 'Hungary',                                                     Alpha2= 'HU', Alpha3 = 'HUN', Numeric = '348'},
{name  = 'Iceland',                                                     Alpha2= 'IS', Alpha3 = 'ISL', Numeric = '352'},
{name  = 'India',                                                       Alpha2= 'IN', Alpha3 = 'IND', Numeric = '356'},
{name  = 'Indonesia',                                                   Alpha2= 'ID', Alpha3 = 'IDN', Numeric = '360'},
{name  = 'Iran (Islamic Republic of)',                                  Alpha2= 'IR', Alpha3 = 'IRN', Numeric = '364'},
{name  = 'Iraq',                                                        Alpha2= 'IQ', Alpha3 = 'IRQ', Numeric = '368'},
{name  = 'Ireland',                                                     Alpha2= 'IE', Alpha3 = 'IRL', Numeric = '372'},
{name  = 'Isle of Man',                                                 Alpha2= 'IM', Alpha3 = 'IMN', Numeric = '833'},
{name  = 'Israel',                                                      Alpha2= 'IL', Alpha3 = 'ISR', Numeric = '376'},
{name  = 'Italy',                                                       Alpha2= 'IT', Alpha3 = 'ITA', Numeric = '380'},
{name  = 'Jamaica',                                                     Alpha2= 'JM', Alpha3 = 'JAM', Numeric = '388'},
{name  = 'Japan',                                                       Alpha2= 'JP', Alpha3 = 'JPN', Numeric = '392'},
{name  = 'Jersey',                                                      Alpha2= 'JE', Alpha3 = 'JEY', Numeric = '832'},
{name  = 'Jordan',                                                      Alpha2= 'JO', Alpha3 = 'JOR', Numeric = '400'},
{name  = 'Kazakhstan',                                                  Alpha2= 'KZ', Alpha3 = 'KAZ', Numeric = '398'},
{name  = 'Kenya',                                                       Alpha2= 'KE', Alpha3 = 'KEN', Numeric = '404'},
{name  = 'Kiribati',                                                    Alpha2= 'KI', Alpha3 = 'KIR', Numeric = '296'},
{name  = 'Korea (the Democratic Peoples Republic of)',                  Alpha2= 'KP', Alpha3 = 'PRK', Numeric = '408'},
{name  = 'Korea (the Republic of)',                                     Alpha2= 'KR', Alpha3 = 'KOR', Numeric = '410'},
{name  = 'Kuwait',                                                      Alpha2= 'KW', Alpha3 = 'KWT', Numeric = '414'},
{name  = 'Kyrgyzstan',                                                  Alpha2= 'KG', Alpha3 = 'KGZ', Numeric = '417'},
{name  = 'Lao Peoples Democratic Republic (the)',                       Alpha2= 'LA', Alpha3 = 'LAO', Numeric = '418'},
{name  = 'Latvia',                                                      Alpha2= 'LV', Alpha3 = 'LVA', Numeric = '428'},
{name  = 'Lebanon',                                                     Alpha2= 'LB', Alpha3 = 'LBN', Numeric = '422'},
{name  = 'Lesotho',                                                     Alpha2= 'LS', Alpha3 = 'LSO', Numeric = '426'},
{name  = 'Liberia',                                                     Alpha2= 'LR', Alpha3 = 'LBR', Numeric = '430'},
{name  = 'Libya',                                                       Alpha2= 'LY', Alpha3 = 'LBY', Numeric = '434'},
{name  = 'Liechtenstein',                                               Alpha2= 'LI', Alpha3 = 'LIE', Numeric = '438'},
{name  = 'Lithuania',                                                   Alpha2= 'LT', Alpha3 = 'LTU', Numeric = '440'},
{name  = 'Luxembourg',                                                  Alpha2= 'LU', Alpha3 = 'LUX', Numeric = '442'},
{name  = 'Macao',                                                       Alpha2= 'MO', Alpha3 = 'MAC', Numeric = '446'},
{name  = 'Madagascar',                                                  Alpha2= 'MG', Alpha3 = 'MDG', Numeric = '450'},
{name  = 'Malawi',                                                      Alpha2= 'MW', Alpha3 = 'MWI', Numeric = '454'},
{name  = 'Malaysia',                                                    Alpha2= 'MY', Alpha3 = 'MYS', Numeric = '458'},
{name  = 'Maldives',                                                    Alpha2= 'MV', Alpha3 = 'MDV', Numeric = '462'},
{name  = 'Mali',                                                        Alpha2= 'ML', Alpha3 = 'MLI', Numeric = '466'},
{name  = 'Malta',                                                       Alpha2= 'MT', Alpha3 = 'MLT', Numeric = '470'},
{name  = 'Marshall Islands (the)',                                      Alpha2= 'MH', Alpha3 = 'MHL', Numeric = '584'},
{name  = 'Martinique',                                                  Alpha2= 'MQ', Alpha3 = 'MTQ', Numeric = '474'},
{name  = 'Mauritania',                                                  Alpha2= 'MR', Alpha3 = 'MRT', Numeric = '478'},
{name  = 'Mauritius',                                                   Alpha2= 'MU', Alpha3 = 'MUS', Numeric = '480'},
{name  = 'Mayotte',                                                     Alpha2= 'YT', Alpha3 = 'MYT', Numeric = '175'},
{name  = 'Mexico',                                                      Alpha2= 'MX', Alpha3 = 'MEX', Numeric = '484'},
{name  = 'Micronesia (Federated States of)',                            Alpha2= 'FM', Alpha3 = 'FSM', Numeric = '583'},
{name  = 'Moldova (the Republic of)',                                   Alpha2= 'MD', Alpha3 = 'MDA', Numeric = '498'},
{name  = 'Monaco',                                                      Alpha2= 'MC', Alpha3 = 'MCO', Numeric = '492'},
{name  = 'Mongolia',                                                    Alpha2= 'MN', Alpha3 = 'MNG', Numeric = '496'},
{name  = 'Montenegro',                                                  Alpha2= 'ME', Alpha3 = 'MNE', Numeric = '499'},
{name  = 'Montserrat',                                                  Alpha2= 'MS', Alpha3 = 'MSR', Numeric = '500'},
{name  = 'Morocco',                                                     Alpha2= 'MA', Alpha3 = 'MAR', Numeric = '504'},
{name  = 'Mozambique',                                                  Alpha2= 'MZ', Alpha3 = 'MOZ', Numeric = '508'},
{name  = 'Myanmar',                                                     Alpha2= 'MM', Alpha3 = 'MMR', Numeric = '104'},
{name  = 'Namibia',                                                     Alpha2= 'NA', Alpha3 = 'NAM', Numeric = '516'},
{name  = 'Nauru',                                                       Alpha2= 'NR', Alpha3 = 'NRU', Numeric = '520'},
{name  = 'Nepal',                                                       Alpha2= 'NP', Alpha3 = 'NPL', Numeric = '524'},
{name  = 'Mauritania',                                                  Alpha2= 'MR', Alpha3 = 'MRT', Numeric = '478'},
{name  = 'Mauritius',                                                   Alpha2= 'MU', Alpha3 = 'MUS', Numeric = '480'}, 

{name  = 'Netherlands (the)',                                           Alpha2= 'NL', Alpha3 = 'NLD', Numeric = '528'},
{name  = 'New Caledonia',                                               Alpha2= 'NC', Alpha3 = 'NCL', Numeric = '540'},
{name  = 'New Zealand',                                                 Alpha2= 'NZ', Alpha3 = 'NZL', Numeric = '554'},
{name  = 'Nicaragua',                                                   Alpha2= 'NI', Alpha3 = 'NIC', Numeric = '558'},
{name  = 'Niger (the)',                                                 Alpha2= 'NE', Alpha3 = 'NER', Numeric = '562'},
{name  = 'Nigeria',                                                     Alpha2= 'NG', Alpha3 = 'NGA', Numeric = '566'},
{name  = 'Niue',                                                        Alpha2= 'NU', Alpha3 = 'NIU', Numeric = '570'},
{name  = 'Norfolk Island',                                              Alpha2= 'NF', Alpha3 = 'NFK', Numeric = '574'},
{name  = 'Northern Mariana Islands (the)',                              Alpha2= 'MP', Alpha3 = 'MNP', Numeric = '580'},
{name  = 'Norway',                                                      Alpha2= 'NO', Alpha3 = 'NOR', Numeric = '578'},
{name  = 'Oman',                                                        Alpha2= 'OM', Alpha3 = 'OMN', Numeric = '512'},
{name  = 'Pakistan',                                                    Alpha2= 'PK', Alpha3 = 'PAK', Numeric = '586'},
{name  = 'Palau',                                                       Alpha2= 'PW', Alpha3 = 'PLW', Numeric = '585'},
{name  = 'Palestine State of',                                          Alpha2= 'PS', Alpha3 = 'PSE', Numeric = '275'},
{name  = 'Panama',                                                      Alpha2= 'PA', Alpha3 = 'PAN', Numeric = '591'},
{name  = 'Papua New Guinea',                                            Alpha2= 'PG', Alpha3 = 'PNG', Numeric = '598'},
{name  = 'Paraguay',                                                    Alpha2= 'PY', Alpha3 = 'PRY', Numeric = '600'},
{name  = 'Peru',                                                        Alpha2= 'PE', Alpha3 = 'PER', Numeric = '604'},
{name  = 'Philippines (the)',                                           Alpha2= 'PH', Alpha3 = 'PHL', Numeric = '608'},
{name  = 'Pitcairn',                                                    Alpha2= 'PN', Alpha3 = 'PCN', Numeric = '612'},
{name  = 'Poland',                                                      Alpha2= 'PL', Alpha3 = 'POL', Numeric = '616'},
{name  = 'Portugal',                                                    Alpha2= 'PT', Alpha3 = 'PRT', Numeric = '620'},
{name  = 'Puerto Rico',                                                 Alpha2= 'PR', Alpha3 = 'PRI', Numeric = '630'},
{name  = 'Qatar',                                                       Alpha2= 'QA', Alpha3 = 'QAT', Numeric = '634'},
{name  = 'Republic of North Macedonia',                                 Alpha2= 'MK', Alpha3 = 'MKD', Numeric = '807'},
{name  = 'Romania',                                                     Alpha2= 'RO', Alpha3 = 'ROU', Numeric = '642'},
{name  = 'Russian Federation (the)',                                    Alpha2= 'RU', Alpha3 = 'RUS', Numeric = '643'},
{name  = 'Rwanda',                                                      Alpha2= 'RW', Alpha3 = 'RWA', Numeric = '646'},
{name  = 'Réunion',                                                     Alpha2= 'RE', Alpha3 = 'REU', Numeric = '638'},
{name  = 'Saint Barthélemy',                                            Alpha2= 'BL', Alpha3 = 'BLM', Numeric = '652'},
{name  = 'Saint Helena Ascension and Tristan da Cunha',                 Alpha2= 'SH', Alpha3 = 'SHN', Numeric = '654'},
{name  = 'Saint Kitts and Nevis',                                       Alpha2= 'KN', Alpha3 = 'KNA', Numeric = '659'},
{name  = 'Saint Lucia',                                                 Alpha2= 'LC', Alpha3 = 'LCA', Numeric = '662'},
{name  = 'Saint Martin (French part)',                                  Alpha2= 'MF', Alpha3 = 'MAF', Numeric = '663'},
{name  = 'Saint Pierre and Miquelon',                                   Alpha2= 'PM', Alpha3 = 'SPM', Numeric = '666'},
{name  = 'Saint Vincent and the Grenadines',                            Alpha2= 'VC', Alpha3 = 'VCT', Numeric = '670'},
{name  = 'Samoa',                                                       Alpha2= 'WS', Alpha3 = 'WSM', Numeric = '882'},
{name  = 'San Marino',                                                  Alpha2= 'SM', Alpha3 = 'SMR', Numeric = '674'},
{name  = 'Sao Tome and Principe',                                       Alpha2= 'ST', Alpha3 = 'STP', Numeric = '678'},
{name  = 'Saudi Arabia',                                                Alpha2= 'SA', Alpha3 = 'SAU', Numeric = '682'},
{name  = 'Senegal',                                                     Alpha2= 'SN', Alpha3 = 'SEN', Numeric = '686'},
{name  = 'Serbia',                                                      Alpha2= 'RS', Alpha3 = 'SRB', Numeric = '688'},
{name  = 'Seychelles',                                                  Alpha2= 'SC', Alpha3 = 'SYC', Numeric = '690'},
{name  = 'Sierra Leone',                                                Alpha2= 'SL', Alpha3 = 'SLE', Numeric = '694'},
{name  = 'Singapore',                                                   Alpha2= 'SG', Alpha3 = 'SGP', Numeric = '702'},
{name  = 'Sint Maarten (Dutch part)',                                   Alpha2= 'SX', Alpha3 = 'SXM', Numeric = '534'},
{name  = 'Slovakia',                                                    Alpha2= 'SK', Alpha3 = 'SVK', Numeric = '703'},
{name  = 'Slovenia',                                                    Alpha2= 'SI', Alpha3 = 'SVN', Numeric = '705'},
{name  = 'Solomon Islands',                                             Alpha2= 'SB', Alpha3 = 'SLB', Numeric = '090'},
{name  = 'Somalia',                                                     Alpha2= 'SO', Alpha3 = 'SOM', Numeric = '706'},
{name  = 'South Africa',                                                Alpha2= 'ZA', Alpha3 = 'ZAF', Numeric = '710'},
{name  = 'South Georgia and the South Sandwich Islands',                Alpha2= 'GS', Alpha3 = 'SGS', Numeric = '239'},
{name  = 'South Sudan',                                                 Alpha2= 'SS', Alpha3 = 'SSD', Numeric = '728'},
{name  = 'Spain',                                                       Alpha2= 'ES', Alpha3 = 'ESP', Numeric = '724'},
{name  = 'Sri Lanka',                                                   Alpha2= 'LK', Alpha3 = 'LKA', Numeric = '144'},
{name  = 'Sudan (the)',                                                 Alpha2= 'SD', Alpha3 = 'SDN', Numeric = '729'},
{name  = 'Suriname',                                                    Alpha2= 'SR', Alpha3 = 'SUR', Numeric = '740'},
{name  = 'Svalbard and Jan Mayen',                                      Alpha2= 'SJ', Alpha3 = 'SJM', Numeric = '744'},
{name  = 'Sweden',                                                      Alpha2= 'SE', Alpha3 = 'SWE', Numeric = '752'},
{name  = 'Switzerland',                                                 Alpha2= 'CH', Alpha3 = 'CHE', Numeric = '756'},
{name  = 'Syrian Arab Republic',                                        Alpha2= 'SY', Alpha3 = 'SYR', Numeric = '760'},
{name  = 'Taiwan (Province of China)',                                  Alpha2= 'TW', Alpha3 = 'TWN', Numeric = '158'},
{name  = 'Tajikistan',                                                  Alpha2= 'TJ', Alpha3 = 'TJK', Numeric = '762'},
{name  = 'Tanzania United Republic of',                                 Alpha2= 'TZ', Alpha3 = 'TZA', Numeric = '834'},
{name  = 'Thailand',                                                    Alpha2= 'TH', Alpha3 = 'THA', Numeric = '764'},
{name  = 'Timor-Leste',                                                 Alpha2= 'TL', Alpha3 = 'TLS', Numeric = '626'},
{name  = 'Togo',                                                        Alpha2= 'TG', Alpha3 = 'TGO', Numeric = '768'},
{name  = 'Tokelau',                                                     Alpha2= 'TK', Alpha3 = 'TKL', Numeric = '772'},
{name  = 'Tonga',                                                       Alpha2= 'TO', Alpha3 = 'TON', Numeric = '776'},
{name  = 'Trinidad and Tobago',                                         Alpha2= 'TT', Alpha3 = 'TTO', Numeric = '780'},
{name  = 'Tunisia',                                                     Alpha2= 'TN', Alpha3 = 'TUN', Numeric = '788'},
{name  = 'Turkey',                                                      Alpha2= 'TR', Alpha3 = 'TUR', Numeric = '792'},
{name  = 'Turkmenistan',                                                Alpha2= 'TM', Alpha3 = 'TKM', Numeric = '795'},
{name  = 'Turks and Caicos Islands (the)',                              Alpha2= 'TC', Alpha3 = 'TCA', Numeric = '796'},
{name  = 'Tuvalu',                                                      Alpha2= 'TV', Alpha3 = 'TUV', Numeric = '798'},
{name  = 'Uganda',                                                      Alpha2= 'UG', Alpha3 = 'UGA', Numeric = '800'},
{name  = 'Ukraine',                                                     Alpha2= 'UA', Alpha3 = 'UKR', Numeric = '804'},
{name  = 'United Arab Emirates (the)',                                  Alpha2= 'AE', Alpha3 = 'ARE', Numeric = '784'},
{name  = 'United Kingdom of Great Britain and  Northern Ireland (the)', Alpha2= 'GB', Alpha3 = 'GBR', Numeric = '826'},
{name  = 'United States Minor Outlying Islands (the)',                  Alpha2= 'UM', Alpha3 = 'UMI', Numeric = '581'},
{name  = 'United States of America (the)',                              Alpha2= 'US', Alpha3 = 'USA', Numeric = '840'},
{name  = 'Uruguay',                                                     Alpha2= 'UY', Alpha3 = 'URY', Numeric = '858'},
{name  = 'Uzbekistan',                                                  Alpha2= 'UZ', Alpha3 = 'UZB', Numeric = '860'},
{name  = 'Vanuatu',                                                     Alpha2= 'VU', Alpha3 = 'VUT', Numeric = '548'},
{name  = 'Venezuela (Bolivarian Republic of)',                          Alpha2= 'VE', Alpha3 = 'VEN', Numeric = '862'},
{name  = 'Viet Nam',                                                    Alpha2= 'VN', Alpha3 = 'VNM', Numeric = '704'},
{name  = 'Virgin Islands (British)',                                    Alpha2= 'VG', Alpha3 = 'VGB', Numeric = '092'},
{name  = 'Virgin Islands (U.S.)',                                       Alpha2= 'VI', Alpha3 = 'VIR', Numeric = '850'},
{name  = 'Wallis and Futuna',                                           Alpha2= 'WF', Alpha3 = 'WLF', Numeric = '876'},
{name  = 'Western Sahara',                                              Alpha2= 'EH', Alpha3 = 'ESH', Numeric = '732'},
{name  = 'Yemen',                                                       Alpha2= 'YE', Alpha3 = 'YEM', Numeric = '887'},
{name  = 'Zambia',                                                      Alpha2= 'ZM', Alpha3 = 'ZMB', Numeric = '894'},
{name  = 'Zimbabwe',                                                    Alpha2= 'ZW', Alpha3 = 'ZWE', Numeric = '716'},
{name  = 'Åland Islands',                                               Alpha2= 'AX', Alpha3 = 'ALA', Numeric = '248'}
]
